site_name: NativePHP for ThinkPHP
site_description: 使用 ThinkPHP 构建桌面应用程序
site_author: NativePHP Team
site_url: https://nativephp.thinkphp.cn

repo_name: nativephp/thinkphp
repo_url: https://github.com/nativephp/thinkphp
edit_uri: edit/master/docs/

theme:
  name: material
  language: zh
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - assets/js/main.js
      css_files:
        - assets/css/main.css

nav:
  - 首页: index.md
  - 安装和配置: installation.md
  - 基础功能: basic-features.md
  - 高级功能: advanced-features.md
  - 扩展功能: extension-features.md
  - 示例应用: example-apps.md
  - API 参考:
    - Alert: api/alert.md
    - App: api/app.md
    - Clipboard: api/clipboard.md
    - ContextMenu: api/context-menu.md
    - Database: api/database.md
    - Device: api/device.md
    - Dialog: api/dialog.md
    - FileSystem: api/file-system.md
    - Geolocation: api/geolocation.md
    - GlobalShortcut: api/global-shortcut.md
    - Http: api/http.md
    - Logger: api/logger.md
    - Menu: api/menu.md
    - Notification: api/notification.md
    - Printer: api/printer.md
    - Process: api/process.md
    - ProgressBar: api/progress-bar.md
    - PushNotification: api/push-notification.md
    - Screen: api/screen.md
    - Settings: api/settings.md
    - Shell: api/shell.md
    - Speech: api/speech.md
    - System: api/system.md
    - Tray: api/tray.md
    - Updater: api/updater.md
    - Window: api/window.md
    - Cache: api/cache.md
    - Event: api/event.md
    - Config: api/config.md
  - 贡献指南: contributing.md
  - 常见问题: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nativephp/thinkphp
    - icon: fontawesome/brands/php
      link: https://www.php.net
    - icon: fontawesome/brands/laravel
      link: https://nativephp.com

copyright: Copyright &copy; 2023 NativePHP Team
